#!/bin/bash
#
#       Pasar actionscript a javascript
#
#

find ./ -iname "*as" | while read ARCHIVO; do
        archivo_base="$(echo $ARCHIVO | sed 's/^\.\///g; s/^\(.*\)\..*$/\1/')"
        echo $archivo_base
        sed 's/#include "\(.*\)\.as"/include ("\1.js");/' $ARCHIVO > "$archivo_base.js"
done
